### ISSUE TITLE
Bug: Restrict OTP textbox to 6 digits

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#105]
would it be better to fix the OTP text length to 6 digits ?

**Comment by kshitijbhardwaj** [comment]
Fixed

**Comment by bevanamit** [comment]
Only numbers should be allowed

**Comment by kshitijbhardwaj** [comment]
I have implemented the length as discussed for mobile number in register page.

**Comment by theheapdump** [comment]
@bevanamit - if not fixed , remove and let the backlog be there

**Comment by bevanamit** [comment]
tested
