### ISSUE TITLE
Bug: Logout is OLD lets use a Icon to show exit 

### ISSUE THREAD

**Issue by bevanamit** [theheapdump/kite-webapp#72]
Logout is OLD lets use a Icon to show exit

**Comment by kshitijbhardwaj** [comment]
Fixed

**Comment by bevanamit** [comment]
Do I have the latest build available to test??

**Comment by bevanamit** [comment]
Issue still persists

![image](https://user-images.githubusercontent.com/5267251/99631684-042aaf80-2a62-11eb-8e77-3192860c7cc8.png)

**Comment by kshitijbhardwaj** [comment]
this is the standard way of showing the logout. I don't know what you want here.

**Comment by bevanamit** [comment]
Sorry.. I meant the image

**Comment by theheapdump** [comment]
i will fix this from backend - access to image is not there.

**Comment by bevanamit** [comment]
![image](https://user-images.githubusercontent.com/5267251/100463124-5b2f2500-30f1-11eb-9df0-959c86d236cc.png)
